- hosts: all
  become: true

  tasks:
    - name: Ensure cgroup Kernel Params
      failed_when: false
      lineinfile:
        backrefs: yes
        line: '\g<1> cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1\g<2>'
        path: '/boot/firmware/cmdline.txt'
        regexp: '^(.*\bconsole=tty1\b).*( root=LABEL\b.*)$'
      with_items:
        - cmdline.txt
        - nobtcmd.txt
    - meta: flush_handlers
    
    - name: Disable Swap
      shell: swapoff -a

    - name: Comment Swap Entries in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '(.*swap*)'
        replace: '#\1'

    - name: Install Docker
      apt:
        name:
          - "docker.io"

    - name: Start Docker
      systemd:
        state: started
        name: docker
        enabled: yes

    - name: Add apt-key for Kubernetes
      apt_key:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

    - name: Add apt-repository for Kubernetes
      apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        update_cache: yes

    - name: Install Kubernetes
      apt:
        install_recommends: no
        name:
          - "kubeadm"
          - "kubectl"
          - "kubelet"
          
    - name: Reboot
      reboot:

